export type MusicAlbum = {
  id: string;
  code: string;
  title: string;
  artist: string;
  previewTitle: string;
  mood: string;
  source: string;
  cover: string;
  durationSeconds: number;
};

export const musicAlbums: MusicAlbum[] = [
  {
    id: "yeah-just-driving",
    code: "01",
    title: "Yeah... Just Driving",
    artist: "MiaoMeowMew",
    previewTitle: "late road sketch",
    mood: "warm night / soft engine / road loop",
    source: "/audio/music/yeah-just-driving.mp3",
    cover: "/music-covers/yeah-just-driving.jpg",
    durationSeconds: 149.64,
  },
  {
    id: "deconstructed",
    code: "02",
    title: "Deconstructed",
    artist: "MiaoMeowMew",
    previewTitle: "broken-pop reconstruction",
    mood: "fracture / pulse / metallic room",
    source: "/audio/music/deconstructed.mp3",
    cover: "/music-covers/deconstructed.jpg",
    durationSeconds: 251.84,
  },
  {
    id: "neon-blade",
    code: "03",
    title: "NEON BLADE",
    artist: "MiaoMeowMew",
    previewTitle: "\u9713\u8679\u5203",
    mood: "neon / blade / fast city",
    source: "/audio/music/neon-blade.mp3",
    cover: "/music-covers/neon-blade.jpg",
    durationSeconds: 126.12,
  },
  {
    id: "the-crown-50s-edit",
    code: "04",
    title: "The Crown",
    artist: "MiaoMeowMew",
    previewTitle: "50s Edit",
    mood: "old radio / crown light / velvet",
    source: "/audio/music/the-crown-50s-edit.mp3",
    cover: "/music-covers/the-crown-50s-edit.jpg",
    durationSeconds: 66.6,
  },
  {
    id: "the-mobius-mirror",
    code: "05",
    title: "The Mobius Mirror",
    artist: "MiaoMeowMew",
    previewTitle: "mirror loop",
    mood: "loop / reflection / silver hallway",
    source: "/audio/music/the-mobius-mirror.mp3",
    cover: "/music-covers/the-mobius-mirror.jpg",
    durationSeconds: 132.04,
  },
  {
    id: "vhs-memory-001",
    code: "06",
    title: "VHS Memory_001",
    artist: "MiaoMeowMew",
    previewTitle: "\u5f55\u50cf\u5e26\u8bb0\u5fc6_001",
    mood: "tape grain / memory / low glow",
    source: "/audio/music/vhs-memory-001.mp3",
    cover: "/music-covers/vhs-memory-001.jpg",
    durationSeconds: 149.88,
  },
  {
    id: "zombie-gym",
    code: "07",
    title: "Zombie Gym",
    artist: "MiaoMeowMew",
    previewTitle: "deadpan workout",
    mood: "comic horror / sweat / beat",
    source: "/audio/music/zombie-gym.mp3",
    cover: "/music-covers/zombie-gym.jpg",
    durationSeconds: 111.48,
  },
  {
    id: "liquid-diamond",
    code: "08",
    title: "Liquid Diamond",
    artist: "MiaoMeowMew",
    previewTitle: "\u6d41\u4f53\u94bb\u77f3",
    mood: "glass / liquid / bright edge",
    source: "/audio/music/liquid-diamond.mp3",
    cover: "/music-covers/liquid-diamond.jpg",
    durationSeconds: 166.92,
  },
  {
    id: "one-dream-thousand-years",
    code: "09",
    title: "\u4e00\u68a6\u5343\u5e74",
    artist: "MiaoMeowMew",
    previewTitle: "edit",
    mood: "ancient dream / soft dust / time fold",
    source: "/audio/music/one-dream-thousand-years.mp3",
    cover: "/music-covers/one-dream-thousand-years.jpg",
    durationSeconds: 206.847,
  },
  {
    id: "disclaimer",
    code: "10",
    title: "\u514d\u8d23\u58f0\u660e",
    artist: "MiaoMeowMew",
    previewTitle: "fine print rhythm",
    mood: "legal joke / dry pulse / black ink",
    source: "/audio/music/disclaimer.mp3",
    cover: "/music-covers/disclaimer.jpg",
    durationSeconds: 214.56,
  },
  {
    id: "wasted-time-with-you",
    code: "11",
    title: "\u6211\u60f3\u548c\u4f60\u865a\u5ea6\u65f6\u5149",
    artist: "MiaoMeowMew",
    previewTitle: "V1",
    mood: "slow afternoon / intimacy / soft clock",
    source: "/audio/music/wasted-time-with-you.mp3",
    cover: "/music-covers/wasted-time-with-you.jpg",
    durationSeconds: 164.6,
  },
  {
    id: "delay",
    code: "12",
    title: "\u62d6\u5ef6",
    artist: "MiaoMeowMew",
    previewTitle: "later, maybe later",
    mood: "loose clock / sticky desk / drift",
    source: "/audio/music/delay.mp3",
    cover: "/music-covers/delay.jpg",
    durationSeconds: 189.96,
  },
  {
    id: "amber-mask",
    code: "13",
    title: "\u7425\u73c0\u91cc\u7684\u5047\u9762",
    artist: "MiaoMeowMew",
    previewTitle: "amber mask",
    mood: "fossil / face / warm resin",
    source: "/audio/music/amber-mask.mp3",
    cover: "/music-covers/amber-mask.jpg",
    durationSeconds: 193.2,
  },
  {
    id: "star-shards",
    code: "14",
    title: "\u788e\u661f",
    artist: "MiaoMeowMew",
    previewTitle: "\u91c7\u68375\u7684\u7248\u672c",
    mood: "broken stars / sample dust / soft shine",
    source: "/audio/music/star-shards.mp3",
    cover: "/music-covers/star-shards.jpg",
    durationSeconds: 162.12,
  },
  {
    id: "neurasthenic-tango",
    code: "15",
    title: "\u795e\u7ecf\u8870\u5f31\u7684\u63a2\u6208",
    artist: "MiaoMeowMew",
    previewTitle: "tango under pressure",
    mood: "tension / dance / tiny panic",
    source: "/audio/music/neurasthenic-tango.mp3",
    cover: "/music-covers/neurasthenic-tango.jpg",
    durationSeconds: 178.76,
  },
  {
    id: "bald-song",
    code: "16",
    title: "\u79c3\u5934\u4e4b\u6b4c",
    artist: "MiaoMeowMew",
    previewTitle: "bald anthem",
    mood: "absurd / funny / bright chorus",
    source: "/audio/music/bald-song.mp3",
    cover: "/music-covers/bald-song.jpg",
    durationSeconds: 193.48,
  },
  {
    id: "ninth-tail",
    code: "17",
    title: "\u7b2c\u4e5d\u6761\u5c3e\u5df4",
    artist: "MiaoMeowMew",
    previewTitle: "ninth tail",
    mood: "myth / tail light / fox shadow",
    source: "/audio/music/ninth-tail.mp3",
    cover: "/music-covers/ninth-tail.jpg",
    durationSeconds: 178.64,
  },
  {
    id: "hair-loss-song",
    code: "18",
    title: "\u8131\u53d1\u4e4b\u6b4c",
    artist: "MiaoMeowMew",
    previewTitle: "hair-loss song",
    mood: "self joke / everyday pop / mirror",
    source: "/audio/music/hair-loss-song.mp3",
    cover: "/music-covers/hair-loss-song.jpg",
    durationSeconds: 184.04,
  },
  {
    id: "ant",
    code: "19",
    title: "\u8682\u8681",
    artist: "MiaoMeowMew",
    previewTitle: "tiny collective",
    mood: "small bodies / busy rhythm / ground view",
    source: "/audio/music/ant.mp3",
    cover: "/music-covers/ant.jpg",
    durationSeconds: 287.12,
  },
];
